development:
  adapter: mysql2
  database: simple_dev
  host: localhost
  encoding: utf8
  username: root
  password: midiland

test:
  adapter: mysql2
  database: simple_test
  host: localhost
  encoding: utf8
  username: root
  password: midiland

production:
  adapter: mysql2
  database: simple
  host: localhost
  encoding: utf8
  username: root
  password: midiland